### ISSUE TITLE
best way to renew a certificate?

### ISSUE THREAD

**Issue by mygnu** [algesten/acme-lib#13]
Hi there, I'm considering this lib to use in my project, how do you renew the cert does [new_order](https://docs.rs/acme-lib/0.7.1/acme_lib/struct.Account.html#method.new_order) renews the cert if its expired?
Thanks

**Comment by Icelk** [comment]
@mygnu What was your conclusion?

**Comment by mygnu** [comment]
@Icelk from memory this is what I did, read the cert you have periodically, if its close to expiry, get a new one and replace.
