### ISSUE TITLE
Please release 0.3.2

### ISSUE THREAD

**Issue by axos88** [algesten/acme-lib#9]
Please release commit 262628fca9db17e5ab831ba1a811d8fdc128648b as 0.3.2
I need to depend on that old version of ring, but need the Fix introduced by that commit to make my life easier.

Thanks,

**Comment by lolgesten** [comment]
Will fix!

**Comment by lolgesten** [comment]
Sorry. I'm understanding what you ask now. You want an old commit release?

Can't you just add a git dependency in your Cargo.toml instead?

I.e.

```toml
acme-lib = { git = "https://github.com/algesten/acme-lib.git", rev = "262628f" }
```

**Comment by axos88** [comment]
Yeah, that's what i did currently. Probably it's fine like that.

**Comment by axos88** [comment]
The only drawback is that whenever my dependencies are relaxed it won't get auto-updated.

**Comment by algesten** [comment]
Ok!
